
services:
  - type: web
    name: vero_bridge_server
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        value: reemplazar_con_tu_api
